name:                pebble-graph
version:             0.1.0.0
# github:              "githubuser/pebble-graph"
license:             BSD-3-Clause
author:              "Joseph Lunderville"
maintainer:          "jlunderv@sfu.ca"
copyright:           "2025 Joseph Lunderville"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Experiment in solving the pebble game as a shortest path problem

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -fno-ignore-asserts
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- FlexibleContexts
- FlexibleInstances
- ImportQualifiedPost
- StandaloneDeriving
- TypeFamilies
- UndecidableInstances

# library:
#   source-dirs: src

executables:
  pebble-graph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    #- pebble-graph

tests:
  pebble-graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    #dependencies:
    #- pebble-graph
